---
- hosts: stereumnodes
  vars_files:
    - /etc/stereum/ethereum2.yaml

  tasks:
    # write config with new template and old settings
    - include_role:
        name: write-config

    # read config file again, make sure all new keys are available to roles
    - include_vars:
        file: /etc/stereum/ethereum2.yaml

    # apply settings
    - include_role:
        name: set-setup
    - include_role:
        name: set-docker-tag
    - include_role:
        name: set-public-ip
    - include_role:
        name: set-override
    - include_role:
        name: set-external-eth1
    - include_role:
        name: set-api-bind-address
    - include_role:
        name: set-graffiti
    - include_role:
        name: configure-autoupdate
    - include_role:
        name: configure-os-security
    - include_role:
        name: configure-ansible
    - include_role:
        name: remove-tmp-password-prysm    

    # update finished
    - name: Unset update in progress
      lineinfile:
        path: "/etc/stereum/ethereum2.yaml"
        regexp: '^\s{2}in_progress:.*'
        line: "  in_progress:"
      become: yes      

    # start node again
    - include_role:
        name: start-services
      
# EOF
