---
- hosts: localhost
  connection: local
  vars_files:
    - /etc/stereum/ethereum2.yaml

  tasks:
    - name: call stop-services role
      include_role:
        name: stop-services

    - name: Set permissions of import folder
      shell: "chown -R {{ stereum_user }}:{{ stereum_user }} {{ e2dc_install_path }}/launchpad"
      when: setup != "multiclient"

    - name: Set permissions for keys to be copied over
      shell: "chown -R {{ stereum_user }}:{{ stereum_user }} {{ validator_keys_path }}/keystore-*.json"
      become: yes

    - name: Copy lanchpad wallet's validator keys
      shell: "cp {{ validator_keys_path }}/keystore-*.json {{ e2dc_install_path }}/launchpad"
      become: yes
      become_user: "{{ stereum_user }}"
      when: setup != "multiclient"

    - name: import to lighthouse
      include_role:
        name: import-validator-keys-lighthouse
      when: setup == "lighthouse"

    - name: import to lodestar
      include_role:
        name: import-validator-keys-lodestar
      when: setup == "lodestar"

    - name: import to nimbus
      include_role:
        name: import-validator-keys-nimbus
      when: setup == "nimbus"

    - name: import to prysm
      include_role:
        name: import-validator-keys-prysm
      when: setup == "prysm"

    - name: import to teku
      include_role:
        name: import-validator-keys-teku
      when: setup == "teku"
    
    - name: import to multiclient
      include_role:
        name: import-validator-keys-multiclient
      when: setup == "multiclient" 

    - name: call start-services role
      include_role:
        name: start-services

# EOF
